version: '3'
services:
  postgres_db:
    image: postgres:10.9-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    volumes:
      - .:/rails_devise_docker
    depends_on:
      - postgres_db
      - cache
    command: bundle exec sidekiq
    environment:
    - REDIS_HOST=cache
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
    - REDIS_HOST=cache
    volumes:
      - .:/rails_devise_docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
      - cache

